<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>dtc_group1-1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="DTC_Group1 1_files/libs/clipboard/clipboard.min.js"></script>
<script src="DTC_Group1 1_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="DTC_Group1 1_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="DTC_Group1 1_files/libs/quarto-html/popper.min.js"></script>
<script src="DTC_Group1 1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="DTC_Group1 1_files/libs/quarto-html/anchor.min.js"></script>
<link href="DTC_Group1 1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="DTC_Group1 1_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="DTC_Group1 1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="DTC_Group1 1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="DTC_Group1 1_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DWI RD Project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<hr>
<ol type="1">
<li><p><strong>Introduction</strong></p>
<p>Drunk driving continues to impose substantial social and economic costs, and legal sanctions are intended to deter repeat offenses. Yet it is difficult to determine whether harsher punishment actually reduces recidivism because drivers who receive more severe penalties often differ systematically from those who receive lighter ones. This paper examines whether crossing the legal blood alcohol concentration (BAC) threshold of 0.08, which triggers stricter DUI penalties, affects the probability that a driver commits another drunk-driving offense. We exploit the fact that the 0.08 rule creates a sharp policy cutoff: drivers just below and just above the threshold should be similar in underlying characteristics, but those above the cutoff face harsher legal consequences. Using a regression discontinuity design, we compare drivers near this threshold to estimate the local causal effect of the policy. By focusing on observations close to the cutoff, the analysis treats the legal threshold as a natural experiment that helps isolate the deterrent impact of stricter DUI punishment on future recidivism.</p></li>
<li><p><strong>Background and policy context.</strong></p>
<p>In Washington State, the legal DUI threshold for adults has been BAC 0.08 since January 1, 1999. Drivers at or above that cutoff face a DUI charge and substantially harsher statutory sanctions than drivers just below it, including higher minimum fines, mandatory jail time or home monitoring, license suspension, and insurance requirements. For a first offense, the statutory minimum penalty rises from $865.50 with 24 hours minimum jail and a 90-day license suspension at BAC 0.08–0.15, with sanctions structured to escalate further for repeat offenders. Because punishment changes discretely at 0.08 while drivers very near the cutoff should otherwise be similar, crossing that threshold creates the policy discontinuity that makes the regression discontinuity design plausible in this setting.</p></li>
<li><p><strong>Data</strong></p>
<p>We use the DWI_Data.rdata subset of Hansen’s Washington State impaired-driving data, which contains 214,558 traffic stops in our working sample and is designed to study whether harsher punishment affects later recidivism. The key variables are the two BAC measures, <code>bac1</code> and <code>bac2</code>, the outcome <code>recidivism</code>, and predetermined covariates including <code>male</code>, <code>white</code>, <code>aged</code>, <code>acc</code>, and <code>year</code>. Each driver receives two BAC tests, so to construct a single running variable for the RD design we use <code>bac_min = pmin(bac1, bac2)</code>. This gives one BAC value per stop, avoids treating the same incident as two observations, and uses a conservative classification rule when determining whether a driver falls above or below the 0.08 legal threshold. In the sample, all key analysis variables have zero missingness, so no additional exclusions are required.</p></li>
<li><p><strong>Exploratory Data Analysis</strong></p>
<p>Our exploratory analysis prepares the dataset for the regression discontinuity design and provides an initial understanding of the variables used in the study. First, we construct the running variable by taking the minimum of the two BAC tests (bac_min). Next, we examine the distribution of BAC values and the density of observations near the 0.08 legal threshold to ensure sufficient data around the cutoff. We also compute the baseline recidivism rate to provide context for later estimates. These steps help verify data quality and confirm that the dataset contains enough observations near the policy threshold for a credible RD analysis.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/DWI_data.rdata"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "dwi"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data checks for variable accuracy</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: inspect-and-check</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># structure check</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dwi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 214,558
Columns: 11
$ Date       &lt;chr&gt; "30jul2007", "20feb2007", "18mar2003", "17dec2006", "07apr1…
$ Alcohol1   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Alcohol2   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ male       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,…
$ white      &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,…
$ recidivism &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ acc        &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,…
$ aged       &lt;dbl&gt; 48, 51, 68, 51, 22, 49, 63, 49, 21, 39, 26, 33, 24, 50, 43,…
$ year       &lt;dbl&gt; 2007, 2007, 2003, 2006, 1999, 2003, 2004, 2005, 1999, 2007,…
$ bac1       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ bac2       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># variables check</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>required_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"bac1"</span>, <span class="st">"bac2"</span>, <span class="st">"recidivism"</span>, <span class="st">"male"</span>, <span class="st">"white"</span>, <span class="st">"aged"</span>, <span class="st">"acc"</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>missing_vars <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(required_vars, <span class="fu">names</span>(dwi))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing_vars) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"Missing required variables: "</span>, <span class="fu">paste</span>(missing_vars, <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"All required variables are present.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>All required variables are present.</code></pre>
</div>
</div>
<section id="key-rdd-variables-running-variable-and-cutoffs" class="level4">
<h4 class="anchored" data-anchor-id="key-rdd-variables-running-variable-and-cutoffs">4.1. Key RDD variables (running variable and cutoffs)</h4>
<p>According to the dataset, each driver has two BAC tests, <code>bac1</code> and <code>bac2</code>. To create one running variable for the RDD, we use the minimum of the two tests (<code>bac_min</code>) because the minimum BAC reading is the measure that determines guilt relative to the legal threshold in the original Hansen setting, and using it provides a conservative classification rule that avoids assigning drivers above 0.08 based on small measurement differences between the two tests. As a result, <code>bac_min</code> is the running variable most closely aligned with the policy rule that generates harsher punishment.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>dwi <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">bac_min =</span> <span class="fu">pmin</span>(bac1, bac2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">above_08 =</span> <span class="fu">as.integer</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.08</span>),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">bac_centered_08 =</span> bac_min <span class="sc">-</span> <span class="fl">0.08</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity checks</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dwi<span class="sc">$</span>bac_min)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.1030  0.1360  0.1393  0.1730  0.4350 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(dwi<span class="sc">$</span>above_08, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
 24807 189751 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dwi<span class="sc">$</span>bac_centered_08)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-0.08000  0.02300  0.05600  0.05928  0.09300  0.35500 </code></pre>
</div>
</div>
</section>
<section id="initial-exploration-bac-distribution-and-baseline-recidivism" class="level4">
<h4 class="anchored" data-anchor-id="initial-exploration-bac-distribution-and-baseline-recidivism">4.2. Initial exploration (BAC distribution and baseline recidivism)</h4>
<p>We begin with basic exploration to understand- (i) the distribution of the running variable (<code>bac_min</code>), (ii) how much data lies near the 0.08 policy cutoff, (iii) the overall baseline recidivism rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dwi, <span class="fu">aes</span>(<span class="at">x =</span> bac_min)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">alpha =</span> <span class="fl">0.45</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.08</span>, <span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"firebrick3"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.30</span>)) <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"BAC distribution (minimum of two tests)"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Dashed lines mark policy thresholds at 0.08"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BAC (bac_min)"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_Group1-1_files/figure-html/bac-distribution-overall-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bac-distribution-near-the-0.08-cutoff" class="level4">
<h4 class="anchored" data-anchor-id="bac-distribution-near-the-0.08-cutoff">4.3. BAC distribution near the 0.08 cutoff</h4>
<p>To check for unusual “bunching” right at the legal threshold, we zoom in on a narrow window around BAC = 0.08.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dwi_008 <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.03</span>, bac_min <span class="sc">&lt;=</span> <span class="fl">0.13</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dwi_008, <span class="fu">aes</span>(<span class="at">x =</span> bac_min)) <span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"deepskyblue3"</span>, <span class="at">alpha =</span> <span class="fl">0.45</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.08</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"firebrick3"</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"BAC distribution near the 0.08 cutoff"</span>,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Density plot for bac_min in [0.03, 0.13]; dashed red line at 0.08"</span>,</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BAC (bac_min)"</span>,</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_Group1-1_files/figure-html/bac-zoom-008-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="baseline-recidivism-rate" class="level4">
<h4 class="anchored" data-anchor-id="baseline-recidivism-rate">4.4. Baseline recidivism rate</h4>
<p>As a reference point, we compute the overall recidivism rate in the full sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dwi <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">recidivism_rate =</span> <span class="fu">mean</span>(recidivism, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       n recidivism_rate
1 214558       0.1176325</code></pre>
</div>
</div>
</section>
<section id="missingness-check" class="level4">
<h4 class="anchored" data-anchor-id="missingness-check">4.5. Missingness check</h4>
<p>Before making any data-cleaning decisions, we report how much ‘missingness’ exists in the key analysis variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>key_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"bac1"</span>, <span class="st">"bac2"</span>, <span class="st">"bac_min"</span>, <span class="st">"recidivism"</span>, <span class="st">"male"</span>, <span class="st">"white"</span>, <span class="st">"aged"</span>, <span class="st">"acc"</span>, <span class="st">"year"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>dwi <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(key_vars), <span class="sc">~</span> <span class="fu">mean</span>(<span class="fu">is.na</span>(.)))) <span class="sc">%&gt;%</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"missing_share"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(missing_share))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  variable   missing_share
  &lt;chr&gt;              &lt;dbl&gt;
1 bac1                   0
2 bac2                   0
3 bac_min                0
4 recidivism             0
5 male                   0
6 white                  0
7 aged                   0
8 acc                    0
9 year                   0</code></pre>
</div>
</div>
</section>
<section id="quick-near-cutoff-comparison" class="level4">
<h4 class="anchored" data-anchor-id="quick-near-cutoff-comparison">4.6. Quick near-cutoff comparison</h4>
<p>As an initial descriptive check, we compare observations just below vs just above each cutoff within a narrow window (±0.02 BAC). This is not the final regression discontinuity estimate, but it provides an early sense of whether outcomes and co-variates look similar near the threshold.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fl">0.02</span>  <span class="co"># window size (±0.02)</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>summary_near <span class="ot">&lt;-</span> <span class="cf">function</span>(cutoff) {</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  dwi <span class="sc">%&gt;%</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(bac_min <span class="sc">&gt;=</span> cutoff <span class="sc">-</span> w, bac_min <span class="sc">&lt;=</span> cutoff <span class="sc">+</span> w) <span class="sc">%&gt;%</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">above =</span> <span class="fu">as.integer</span>(bac_min <span class="sc">&gt;=</span> cutoff)) <span class="sc">%&gt;%</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(above) <span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">recid_rate =</span> <span class="fu">mean</span>(recidivism),</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">male_share =</span> <span class="fu">mean</span>(male),</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">white_share =</span> <span class="fu">mean</span>(white),</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean_age =</span> <span class="fu">mean</span>(aged),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">acc_share =</span> <span class="fu">mean</span>(acc),</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">cutoff =</span> cutoff) <span class="sc">%&gt;%</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">relocate</span>(cutoff, above)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary_near</span>(<span class="fl">0.08</span>),</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cutoff, above)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
  cutoff above     n recid_rate male_share white_share mean_age acc_share
   &lt;dbl&gt; &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1   0.08     0 14584     0.115       0.784       0.846     34.5    0.0902
2   0.08     1 25790     0.0989      0.792       0.852     33.9    0.0899</code></pre>
</div>
</div>
<p>At 0.08, recidivism is lower just above the cutoff (≈ 0.0989) than just below (≈ 0.1147).</p>
</section>
<section id="interim-takeaways-from-initial-exploration" class="level4">
<h4 class="anchored" data-anchor-id="interim-takeaways-from-initial-exploration">4.7. Interim takeaways from initial exploration</h4>
<p>At this stage, we have, (i) created the running variable for the regression discontinuity design (<code>bac_min</code>, defined as the minimum of the two BAC tests), (ii) checked basic data quality.</p>
<p>The distribution of <code>bac_min</code> looks smooth overall and around the policy cutoff (0.08) based on the density plots. Missingness is effectively zero in the key variables used in later analysis, so no sample exclusions are required for missing data.</p>
<p>As an initial descriptive comparison within ±0.02 of each cutoff, recidivism appears lower just above 0.08 than just below. These comparisons are descriptive and do not yet isolate the causal effect; they mainly motivate the formal RDD analysis in the next stage.</p>
</section>
<section id="difference-summary-table" class="level4">
<h4 class="anchored" data-anchor-id="difference-summary-table">4.8. Difference summary table</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>near_tbl <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary_near</span>(<span class="fl">0.08</span>),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>near_tbl <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cutoff) <span class="sc">%&gt;%</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_recid =</span> recid_rate[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> recid_rate[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_male  =</span> male_share[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> male_share[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_white =</span> white_share[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> white_share[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_age   =</span> mean_age[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> mean_age[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_acc   =</span> acc_share[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> acc_share[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  cutoff diff_recid diff_male diff_white diff_age  diff_acc
   &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1   0.08    -0.0158   0.00735    0.00596   -0.606 -0.000356</code></pre>
</div>
</div>
</section>
<section id="dag-visualizing-the-causal-relationship" class="level2">
<h2 class="anchored" data-anchor-id="dag-visualizing-the-causal-relationship"><strong>5. DAG: Visualizing the causal relationship</strong></h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="dagitty-model.jpeg" class="img-fluid figure-img" width="734"></p>
<figcaption><em>Figure. 6. Simplified DAG showing the Causal logic</em></figcaption>
</figure>
</div>
<p>Figure presents the causal logic behind our regression discontinuity design. BAC is the running variable, and the node BAC ≥ 0.08&nbsp;represents the legal assignment rule that determines whether a driver is exposed to harsher DUI punishment. That punishment is the treatment mechanism through which crossing the threshold may affect future recidivism. The diagram also includes U, which captures unobserved driver characteristics, such as alcohol misuse or alcoholism, impulsiveness, or risk tolerance, that may influence both BAC and the likelihood of reoffending. These unobserved factors create a backdoor path that would bias a simple comparison of drivers with higher and lower BAC levels. By focusing on drivers just below and just above the 0.08 cutoff, the RD design uses the policy cutoff to isolate the local causal effect of harsher punishment on recidivism.</p>
</section>
<section id="causal-logic" class="level2">
<h2 class="anchored" data-anchor-id="causal-logic">5.1. Causal Logic</h2>
<p>Building on the causal structure shown in Figure 6, the key empirical challenge is to isolate the effect of harsher DUI punishment from the characteristics of the drivers who receive it. Drivers with higher BAC levels are more likely to face tougher penalties, but they may also differ in less visible ways, such as impulsiveness, alcohol misuse, or a greater willingness to take risks, that independently increase the likelihood of reoffending. For that reason, a simple comparison between drivers with lower and higher BAC levels would confound the effect of punishment with the effect of those underlying differences.</p>
<p>The 0.08 BAC cutoff helps address this problem. Because Washington State’s DUI penalties increase sharply at that threshold, drivers just below and just above 0.08 should be very similar, while only those above the cutoff receive harsher punishment. This is what makes the setting well suited to a regression discontinuity design: by comparing drivers very close to the threshold, we can use the policy rule as a natural experiment to estimate the local effect of harsher punishment on future recidivism. In the next step, we will be assess whether the assumptions required for that design are supported by the data.</p>
</section>
<section id="identification-assumptions-and-supporting-checks" class="level2">
<h2 class="anchored" data-anchor-id="identification-assumptions-and-supporting-checks">6. Identification Assumptions and Supporting Checks</h2>
</section>
<section id="i.-checking-data-for-lumping" class="level2">
<h2 class="anchored" data-anchor-id="i.-checking-data-for-lumping">i. Checking Data for Lumping</h2>
<p>Now that the data are prepared and the causal logic is clear, the next step is to test whether the key assumptions of the regression discontinuity design are plausible in this setting. Before estimating the treatment effect at the 0.08 BAC cutoff, we need to check that drivers are not systematically sorting to one side of the threshold or the other. We assess this by examining the distribution of the running variable near the cutoff with a lumping test. We also need to verify that drivers just below and just above 0.08 look similar on predetermined characteristics. We assess that by estimating placebo regressions using variables that should not jump at the threshold.</p>
<p>A useful first check is whether there is any manipulation in the running variable around 0.08. To examine this, we graph the BAC distribution using bins and look for any unusual break or bunching in the number of observations right at the cutoff.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check lumping at the 0.08 cutoff</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>dwi_bin_count <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.03</span>, bac_min <span class="sc">&lt;=</span> <span class="fl">0.13</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bac_bins =</span> <span class="fu">cut</span>(bac_min, <span class="at">breaks =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">13</span><span class="sc">/</span><span class="dv">100</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(bac_bins) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create plot to visualize the data</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dwi_bin_count, <span class="fu">aes</span>(<span class="at">x =</span> bac_bins, <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">5.5</span>,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Observation counts near 0.08 BAC cutoff"</span>,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"BAC bin"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_Group1-1_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<pre><code></code></pre>
<p>We use this visual check is used to assess whether there is manipulation of the running variable, a key assumption for a valid regression discontinuity design. If drivers or law enforcement were systematically influencing BAC readings to fall on one side of the threshold, we would expect to observe a sharp spike or drop in the number of observations immediately below or above the cutoff. Instead, the distribution appears smooth, with no noticeable bunching just below 0.08. This suggests that drivers are not sorting around the threshold and that BAC readings near the cutoff are plausibly random. Because the distribution remains continuous at the threshold, the identifying assumption of the RD design appears reasonable, allowing us to proceed with placebo</p>
</section>
<section id="ii.-the-placebo-tests" class="level2">
<h2 class="anchored" data-anchor-id="ii.-the-placebo-tests">6.ii. The Placebo Tests</h2>
<p>Our placebo tests evaluate whether the observations just below and just above the 0.08 BAC cutoff are truly comparable. We run these tests because a valid regression discontinuity design requires that the cutoff changes only the treatment intensity, in this case, harsher punishment, and not other underlying characteristics of the drivers. To check this, we re-estimate the RD specification using predetermined variables such as male, white, aged, and acc as outcomes instead of recidivism. If the design is credible, we should not observe a discontinuous jump at the cutoff for any of these variables. A significant jump would suggest that drivers on either side of 0.08 differ in ways other than punishment, which would weaken the validity of the comparison. Because our analysis focuses on the instructor-approved&nbsp;0.08 threshold, we perform these placebo checks only at that cutoff.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create centered variable for BAC at 0.08 cutoff</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>dwi <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bac_centered_08 =</span> bac_min <span class="sc">-</span> <span class="fl">0.08</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run placebo regressions at the 0.08 cutoff</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">feols</span>(male  <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>),</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(white <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>),</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">feols</span>(aged  <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>),</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">feols</span>(acc   <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08,</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>),</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(p1, p2, p3, p4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           p1                 p2
Dependent Var.:                          male              white
                                                                
Constant                   0.7853*** (0.0045) 0.8478*** (0.0039)
above_08                      0.0057 (0.0055)    0.0038 (0.0049)
bac_centered_08              -0.1752 (0.2330)    0.0552 (0.2052)
above_08 x bac_centered_08    0.2947 (0.2575)    0.0488 (0.2264)
__________________________ __________________ __________________
S.E. type                  Heteroskedas.-rob. Heteroskedas.-rob.
Observations                           92,158             92,158
R2                                    6.05e-5            8.86e-5
Adj. R2                                2.8e-5             5.6e-5

                                          p3                 p4
Dependent Var.:                         aged                acc
                                                               
Constant                   33.92*** (0.1297) 0.0825*** (0.0031)
above_08                    -0.1647 (0.1596)   -0.0022 (0.0039)
bac_centered_08            -66.52*** (7.012) -1.044*** (0.1772)
above_08 x bac_centered_08  73.75*** (7.666)  1.901*** (0.1954)
__________________________ _________________ __________________
S.E. type                  Heteroskeda.-rob. Heteroskedas.-rob.
Observations                          92,158             92,158
R2                                   0.00232            0.00163
Adj. R2                              0.00229            0.00160
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The placebo regression results provide a useful check on whether drivers just below and just above the 0.08 BAC cutoff are comparable. In these models, we replace recidivism with predetermined characteristics, sex, race, age, and accident involvement, and estimate the same regression discontinuity specification used in the main analysis. The coefficient of interest is the indicator for being above the cutoff, since it captures any discrete jump at the threshold. Across these regressions, that coefficient is small and statistically insignificant in every case, suggesting that these observable characteristics do not change abruptly at 0.08. This pattern is consistent with the idea that drivers on either side of the legal threshold are similar in observable ways, which supports the credibility of the regression discontinuity design. We report heteroskedasticity-robust standard errors in the placebo regressions for consistency with the main analysis and because the variance of the error term may differ across observations.</p>
</section>
<section id="regression-discontinuity-specification" class="level2">
<h2 class="anchored" data-anchor-id="regression-discontinuity-specification">7. Regression Discontinuity Specification</h2>
<ol start="7" type="1">
<li><strong>i. The working equation</strong></li>
</ol>
<p><span class="math display">\[
\text{Recidivism}_i = \beta_0 + \beta_1 \text{Above08}_i + \beta_2 (BAC_i - 0.08) + \beta_3 \big[\text{Above08}_i \times (BAC_i - 0.08)\big] + \varepsilon_i
\]</span></p>
<p>To estimate the effect of harsher punishment at the legal threshold, we use a local linear regression discontinuity specification centered at BAC = 0.08. In this model,&nbsp;<code>Above08</code> indicates whether a driver falls at or above the legal cutoff, while the centered BAC term measures distance from the threshold. The interaction term allows the relationship between BAC and recidivism to differ on either side of the cutoff. The coefficient of primary interest is B1​, which captures the discontinuous jump in recidivism at <strong>0.08</strong> and represents the local effect of crossing the legal BAC limit.</p>
</section>
<section id="main-regression-discontinuity-models" class="level2">
<h2 class="anchored" data-anchor-id="main-regression-discontinuity-models">8. Main Regression Discontinuity Models</h2>
<p>Now that we have checked the key assumptions in our data set, we proceed with the main analysis. We want to determine whether crossing the BAC threshold, and receiving a harsh punishment, causes a decrease in recidivism. Firstly, we center the running variable around each cutoff point, creating a treatment indicator for being above the threshold and then interact these two variables. The coefficient on the treatment indicator shows the jump in recidivism at the cutoff, which is our estimate of the effect of a harsher punishment. We then run three different variations for each cutoff: 1) a wider window of 0.05, 2) a narrower window of 0.02, and 3) a wide window with our additional variables added as controls. We then compare the results among these three variations to see if our results are stable.</p>
<ol start="7" type="1">
<li><strong>i. Main RD Estimate at the 0.08 BAC Cutoff (±0.05 Window)</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>r1 <span class="ot">&lt;-</span> <span class="fu">feols</span>(</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  recidivism <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08,</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>),</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">vcov =</span> <span class="st">"hetero"</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                            r1
Dependent Var.:                     recidivism
                                              
Constant                    0.1123*** (0.0034)
above_08                   -0.0188*** (0.0042)
bac_centered_08               -0.2613 (0.1818)
above_08 x bac_centered_08  0.6904*** (0.1998)
__________________________ ___________________
S.E. type                  Heteroskedast.-rob.
Observations                            92,158
R2                                     0.00054
Adj. R2                                0.00051
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Regression table 1.</p>
<p>We estimate a local linear regression discontinuity model within a ±0.05 window around the 0.08 BAC cutoff to compare drivers who are closest to the legal threshold. This choice is justified because RD relies on local comparisons, where observations just below and just above the cutoff are most plausibly similar except for the harsher punishment triggered at 0.08. The interaction between above_08 and bac_centered_08 allows the BAC–recidivism relationship to differ on either side of the threshold while identifying the jump at the cutoff. The coefficient on above_08 is -0.0188 and statistically significant, indicating that drivers just above 0.08 have an estimated recidivism rate about 1.9 percentage points lower than comparable drivers just below the cutoff.</p>
<ol start="7" type="1">
<li><strong>ii. Robustness Check: Narrower Bandwidth (±0.02)</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(recidivism <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.02</span>), <span class="at">vcov =</span><span class="st">"hetero"</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           r2
Dependent Var.:                    recidivism
                                             
Constant                   0.1074*** (0.0046)
above_08                    -0.0133* (0.0061)
bac_centered_08             -0.8974. (0.4699)
above_08 x bac_centered_08    1.262* (0.5847)
__________________________ __________________
S.E. type                  Heteroskedas.-rob.
Observations                           38,962
R2                                    0.00083
Adj. R2                               0.00075
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>We use a bandwidth of ±0.02 around the 0.08 cutoff, meaning the estimation sample includes drivers with BAC values between&nbsp;0.06 and 0.10. This narrower specification serves as a robustness check by focusing on observations even closer to the threshold, where drivers just below and just above 0.08 are most plausibly comparable. In this model, the coefficient on&nbsp;<code>above_08</code> is −0.0133 and remains statistically significant at the 5 percent level. This implies that drivers just above the legal cutoff have an estimated recidivism rate about 1.3 percentage points lower than those just below it, reinforcing the main deterrence result from the wider bandwidth specification.</p>
<ol start="7" type="1">
<li><strong>iii. Robustness Check: RD Estimate with Demographic Controls</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>r3 <span class="ot">&lt;-</span> <span class="fu">feols</span>(recidivism <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08 <span class="sc">+</span> male <span class="sc">+</span> white <span class="sc">+</span> aged,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>), <span class="at">vcov =</span> <span class="st">"hetero"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                             r3
Dependent Var.:                      recidivism
                                               
Constant                     0.1019*** (0.0052)
above_08                    -0.0192*** (0.0042)
bac_centered_08               -0.3129. (0.1815)
male                         0.0331*** (0.0023)
white                        0.0157*** (0.0028)
aged                       -0.0009*** (8.39e-5)
above_08 x bac_centered_08   0.7427*** (0.1995)
__________________________ ____________________
S.E. type                  Heteroskedasti.-rob.
Observations                             92,158
R2                                      0.00360
Adj. R2                                 0.00353
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The above regression adds male, white, and age as controls within the same ±0.05 bandwidth around the 0.08 cutoff. In an RD design, these controls are not needed for identification if the continuity assumption holds, but they are useful as a robustness check because they can improve precision and show whether the estimated jump is sensitive to modest covariate adjustment. The coefficient on <code>above_08</code> is -0.0192, nearly identical to the baseline estimate of -0.0188. This stability suggests that the main result is not being driven by observable demographic differences, strengthening the interpretation that crossing 0.08 reduces recidivism locally.</p>
</section>
<section id="results-and-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="results-and-interpretation">8. Results and Interpretation</h2>
<ol start="8" type="1">
<li><strong>i. RD plot of recidivism around 0.08 cutoff.</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: rd-plot-recidivism</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>dwi <span class="sc">%&gt;%</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>) <span class="sc">%&gt;%</span>   <span class="co"># same bandwidth as main regression</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bac_centered_08, <span class="at">y =</span> recidivism)) <span class="sc">+</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># binned means</span></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary_bin</span>(</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">30</span>,</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> mean,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># fitted line left of cutoff</span></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(bac_centered_08 <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> <span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>),</span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"steelblue"</span></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># fitted line right of cutoff</span></span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(bac_centered_08 <span class="sc">&gt;=</span> <span class="dv">0</span> <span class="sc">&amp;</span> <span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>),</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span></span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Recidivism Around the 0.08 BAC Cutoff"</span>,</span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BAC centered at 0.08"</span>,</span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Recidivism Rate"</span></span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="DTC_Group1-1_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure</em> <em>9. RD plot of recidivism around 0.08 cutoff.</em></p>
<p>Figure 9 presents a binned scatter plot of recidivism rates against BAC centered at the 0.08 legal threshold. Each point represents the mean recidivism rate within a small BAC bin, while the fitted lines show local linear trends on either side of the cutoff. The vertical dashed line marks the legal threshold. The figure shows a visible downward jump in recidivism immediately after the cutoff, indicating that drivers just above 0.08 have lower subsequent recidivism than those just below it. This visual pattern is consistent with the deterrence effect estimated in the regression results.</p>
<ol start="8" type="1">
<li><strong>ii. Results and Interpretation</strong></li>
</ol>
<p>Putting the results together, the evidence consistently points to a deterrent effect at the 0.08 BAC cutoff. Across the main specification, the narrower bandwidth check, and the model with demographic controls, the estimated coefficient on above_08 remains negative and statistically significant. The preferred interpretation is that drivers just above 0.08 have a recidivism rate roughly 1.3 to 1.9 percentage points lower&nbsp;than comparable drivers just below the cutoff. Because this pattern is stable across reasonable specifications, the findings support the conclusion that the harsher DUI punishment triggered at 0.08 reduces future drunk-driving recidivism for drivers near the legal threshold.</p>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">9. Limitations</h2>
<p>While the regression discontinuity design provides credible causal identification near the cutoff, the estimates should be interpreted as local effects. Specifically, the results describe the behavior of drivers whose BAC levels fall very close to the 0.08 threshold and may not generalize to drivers with substantially higher or lower BAC levels. In addition, the policy change captured by the cutoff represents a bundle of sanctions, including fines, license suspension, and potential jail time, making it difficult to isolate which component drives the deterrence effect. Despite these limitations, the smooth density of the running variable and the placebo test results support the credibility of the RD design.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">10. Conclusion</h2>
<p>These findings suggest that legal thresholds in DUI policy can play an important deterrent role. Even relatively small increases in punishment at the legal limit appear to reduce the likelihood of repeat offenses among drivers near the threshold.</p>
<pre><code></code></pre>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>