<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DWI RD Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="writeup_files/libs/clipboard/clipboard.min.js"></script>
<script src="writeup_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="writeup_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="writeup_files/libs/quarto-html/popper.min.js"></script>
<script src="writeup_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="writeup_files/libs/quarto-html/anchor.min.js"></script>
<link href="writeup_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="writeup_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="writeup_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="writeup_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="writeup_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DWI RD Project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>##Setup</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.5     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'fixest' was built under R version 4.5.2</code></pre>
</div>
</div>
<section id="load-dataset" class="level2">
<h2 class="anchored" data-anchor-id="load-dataset">Load dataset</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/DWI_data.rdata"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "dwi"</code></pre>
</div>
</div>
</section>
<section id="data-checks-structure-required-variables" class="level2">
<h2 class="anchored" data-anchor-id="data-checks-structure-required-variables">Data checks (structure + required variables)</h2>
<p>Before creating the RDD variables, I check that the dataset loaded correctly and contains the key fields.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick structure check</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dwi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 214,558
Columns: 11
$ Date       &lt;chr&gt; "30jul2007", "20feb2007", "18mar2003", "17dec2006", "07apr1…
$ Alcohol1   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Alcohol2   &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ male       &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,…
$ white      &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,…
$ recidivism &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ acc        &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,…
$ aged       &lt;dbl&gt; 48, 51, 68, 51, 22, 49, 63, 49, 21, 39, 26, 33, 24, 50, 43,…
$ year       &lt;dbl&gt; 2007, 2007, 2003, 2006, 1999, 2003, 2004, 2005, 1999, 2007,…
$ bac1       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ bac2       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Confirm the required variables exist</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>required_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"bac1"</span>, <span class="st">"bac2"</span>, <span class="st">"recidivism"</span>, <span class="st">"male"</span>, <span class="st">"white"</span>, <span class="st">"aged"</span>, <span class="st">"acc"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>missing_vars <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(required_vars, <span class="fu">names</span>(dwi))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(missing_vars) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"Missing required variables: "</span>, <span class="fu">paste</span>(missing_vars, <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"All required variables are present.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>All required variables are present.</code></pre>
</div>
</div>
</section>
<section id="key-rdd-variables-running-variable-and-cutoffs" class="level2">
<h2 class="anchored" data-anchor-id="key-rdd-variables-running-variable-and-cutoffs">Key RDD variables (running variable and cutoffs)</h2>
<p>Each driver has two BAC tests (<code>bac1</code> and <code>bac2</code>). To create one running variable for the RDD, I use the minimum of the two tests (<code>bac_min</code>). I then create indicators for being at/above the two policy thresholds (0.08 and 0.15).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dwi <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">bac_min  =</span> <span class="fu">pmin</span>(bac1, bac2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">above_08 =</span> <span class="fu">as.integer</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.08</span>),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">above_15 =</span> <span class="fu">as.integer</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.15</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity checks</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dwi<span class="sc">$</span>bac_min)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0000  0.1030  0.1360  0.1393  0.1730  0.4350 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(dwi<span class="sc">$</span>above_08, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
 24807 189751 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(dwi<span class="sc">$</span>above_15, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
     0      1 
128603  85955 </code></pre>
</div>
</div>
</section>
<section id="initial-exploration-bac-distribution-and-baseline-recidivism" class="level2">
<h2 class="anchored" data-anchor-id="initial-exploration-bac-distribution-and-baseline-recidivism">Initial exploration (BAC distribution and baseline recidivism)</h2>
<p>I begin with basic exploration to understand- (i) the distribution of the running variable (<code>bac_min</code>), (ii) how much data lies near each policy cutoff, (iii) the overall baseline recidivism rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dwi, <span class="fu">aes</span>(<span class="at">x =</span> bac_min)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"deepskyblue3"</span>, <span class="at">alpha =</span> <span class="fl">0.45</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.08</span>, <span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"firebrick3"</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.15</span>, <span class="at">linewidth =</span> <span class="fl">1.1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"darkorange3"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.30</span>)) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"BAC distribution (minimum of two tests)"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Dashed lines mark policy thresholds at 0.08 (red) and 0.15 (orange)"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BAC (bac_min)"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="writeup_files/figure-html/bac-distribution-overall-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="bac-distribution-near-the-0.08-cutoff" class="level3">
<h3 class="anchored" data-anchor-id="bac-distribution-near-the-0.08-cutoff">BAC distribution near the 0.08 cutoff</h3>
<p>To check for unusual “bunching” right at the legal threshold, I zoom in on a narrow window around BAC = 0.08.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>dwi_008 <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.03</span>, bac_min <span class="sc">&lt;=</span> <span class="fl">0.13</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dwi_008, <span class="fu">aes</span>(<span class="at">x =</span> bac_min)) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"deepskyblue3"</span>, <span class="at">alpha =</span> <span class="fl">0.45</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.08</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"firebrick3"</span>) <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"BAC distribution near the 0.08 cutoff"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Density plot for bac_min in [0.03, 0.13]; dashed red line at 0.08"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BAC (bac_min)"</span>,</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="writeup_files/figure-html/bac-zoom-008-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="bac-distribution-near-the-0.15-cutoff" class="level3">
<h3 class="anchored" data-anchor-id="bac-distribution-near-the-0.15-cutoff">BAC distribution near the 0.15 cutoff</h3>
<p>I also zoom in around BAC = 0.15, which corresponds to an additional increase in punishment severity. This helps assess whether there is any unusual bunching or discontinuity in the running variable near the second threshold.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dwi_015 <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.10</span>, bac_min <span class="sc">&lt;=</span> <span class="fl">0.20</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dwi_015, <span class="fu">aes</span>(<span class="at">x =</span> bac_min)) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"darkorange2"</span>, <span class="at">alpha =</span> <span class="fl">0.40</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.15</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"firebrick3"</span>) <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"BAC distribution near the 0.15 cutoff"</span>,</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Density plot for bac_min in [0.10, 0.20]; dashed red line at 0.15"</span>,</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"BAC (bac_min)"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Density"</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="writeup_files/figure-html/bac-zoom-015-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="baseline-recidivism-rate" class="level3">
<h3 class="anchored" data-anchor-id="baseline-recidivism-rate">Baseline recidivism rate</h3>
<p>As a reference point, I compute the overall recidivism rate in the full sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>dwi <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">recidivism_rate =</span> <span class="fu">mean</span>(recidivism, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       n recidivism_rate
1 214558       0.1176325</code></pre>
</div>
</div>
</section>
</section>
<section id="missingness-check" class="level2">
<h2 class="anchored" data-anchor-id="missingness-check">Missingness check</h2>
<p>Before making any data-cleaning decisions, I report how much ‘missingness’ exists in the key analysis variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>key_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"bac1"</span>, <span class="st">"bac2"</span>, <span class="st">"bac_min"</span>, <span class="st">"recidivism"</span>, <span class="st">"male"</span>, <span class="st">"white"</span>, <span class="st">"aged"</span>, <span class="st">"acc"</span>, <span class="st">"year"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>dwi <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(key_vars), <span class="sc">~</span> <span class="fu">mean</span>(<span class="fu">is.na</span>(.)))) <span class="sc">%&gt;%</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"missing_share"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(missing_share))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  variable   missing_share
  &lt;chr&gt;              &lt;dbl&gt;
1 bac1                   0
2 bac2                   0
3 bac_min                0
4 recidivism             0
5 male                   0
6 white                  0
7 aged                   0
8 acc                    0
9 year                   0</code></pre>
</div>
</div>
</section>
<section id="quick-near-cutoff-comparison" class="level2">
<h2 class="anchored" data-anchor-id="quick-near-cutoff-comparison">Quick near-cutoff comparison</h2>
<p>As an initial descriptive check, I compare observations just below vs just above each cutoff within a narrow window (±0.02 BAC). This is not the final regression discontinuity estimate, but it provides an early sense of whether outcomes and co-variates look similar near the threshold.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fl">0.02</span>  <span class="co"># window size (±0.02)</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>summary_near <span class="ot">&lt;-</span> <span class="cf">function</span>(cutoff) {</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  dwi <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(bac_min <span class="sc">&gt;=</span> cutoff <span class="sc">-</span> w, bac_min <span class="sc">&lt;=</span> cutoff <span class="sc">+</span> w) <span class="sc">%&gt;%</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">above =</span> <span class="fu">as.integer</span>(bac_min <span class="sc">&gt;=</span> cutoff)) <span class="sc">%&gt;%</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(above) <span class="sc">%&gt;%</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">recid_rate =</span> <span class="fu">mean</span>(recidivism),</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">male_share =</span> <span class="fu">mean</span>(male),</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">white_share =</span> <span class="fu">mean</span>(white),</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">mean_age =</span> <span class="fu">mean</span>(aged),</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">acc_share =</span> <span class="fu">mean</span>(acc),</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">cutoff =</span> cutoff) <span class="sc">%&gt;%</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">relocate</span>(cutoff, above)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a><span class="fu">bind_rows</span>(</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary_near</span>(<span class="fl">0.08</span>),</span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary_near</span>(<span class="fl">0.15</span>)</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(cutoff, above)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 8
  cutoff above     n recid_rate male_share white_share mean_age acc_share
   &lt;dbl&gt; &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1   0.08     0 14584     0.115       0.784       0.846     34.5    0.0902
2   0.08     1 25790     0.0989      0.792       0.852     33.9    0.0899
3   0.15     0 32208     0.116       0.791       0.863     34.3    0.133 
4   0.15     1 28376     0.117       0.788       0.870     34.9    0.162 </code></pre>
</div>
</div>
<p>At 0.08, recidivism is lower just above the cutoff (≈ 0.0989) than just below (≈ 0.1147). At 0.15, recidivism is very similar (slightly higher above).</p>
</section>
<section id="interim-takeaways-from-initial-exploration" class="level2">
<h2 class="anchored" data-anchor-id="interim-takeaways-from-initial-exploration">Interim takeaways from initial exploration</h2>
<p>At this stage, I have- (i) created the running variable for the regression discontinuity design (<code>bac_min</code>, defined as the minimum of the two BAC tests), (ii) checked basic data quality.</p>
<p>The distribution of <code>bac_min</code> looks smooth overall and around both policy cutoffs (0.08 and 0.15) based on the density plots. ‘Missingness’ is effectively zero in the key variables used in later analysis, so no sample exclusions are required for missing data.</p>
<p>As an initial descriptive comparison within ±0.02 of each cutoff, recidivism appears lower just above 0.08 than just below, while around 0.15 the difference is small. These comparisons are descriptive and do not yet isolate the causal effect; they mainly motivate the formal RDD analysis in the next stage.</p>
</section>
<section id="difference-summary-table" class="level2">
<h2 class="anchored" data-anchor-id="difference-summary-table">Difference summary table</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>near_tbl <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary_near</span>(<span class="fl">0.08</span>),</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary_near</span>(<span class="fl">0.15</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>near_tbl <span class="sc">%&gt;%</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(cutoff) <span class="sc">%&gt;%</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_recid =</span> recid_rate[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> recid_rate[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_male  =</span> male_share[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> male_share[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_white =</span> white_share[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> white_share[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_age   =</span> mean_age[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> mean_age[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">diff_acc   =</span> acc_share[above <span class="sc">==</span> <span class="dv">1</span>] <span class="sc">-</span> acc_share[above <span class="sc">==</span> <span class="dv">0</span>],</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  cutoff diff_recid diff_male diff_white diff_age  diff_acc
   &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1   0.08   -0.0158    0.00735    0.00596   -0.606 -0.000356
2   0.15    0.00128  -0.00277    0.00775    0.516  0.0294  </code></pre>
</div>
</div>
</section>
<section id="checking-data-for-lumping" class="level2">
<h2 class="anchored" data-anchor-id="checking-data-for-lumping">Checking Data for Lumping</h2>
<p>Now that the data has been cleaned and the causal logic has been explained, we need to test whether the assumptions of the RDD design are present in the data. Before we can begin performing our RDD analysis, we need to make sure that there is no manipulation of BAC that influences whether the drivers end up on one side of the cutoff or the other. This will be achieved with a lumping test. Next, we need to ensure that the drivers just above and below the cutoff are materially similar to each other. We will achieve this by performing placebo regressions.</p>
<p>We need to check that there is no manipulation in the running variable around the cutoff point. To do this, we will graphically look at the data, by creating bins, and check to see if there is a jump at the cutoff in the number of observations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check lumping at the 0.08 cutoff</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dwi_bin_count <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.03</span>, bac_min <span class="sc">&lt;=</span> <span class="fl">0.13</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bac_bins =</span> <span class="fu">cut</span>(bac_min, <span class="at">breaks =</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">13</span><span class="sc">/</span><span class="dv">100</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(bac_bins) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create plot to visualize the data</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dwi_bin_count, <span class="fu">aes</span>(<span class="at">x =</span> bac_bins, <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">5.5</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Observation counts near 0.08 BAC cutoff"</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"BAC bin"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="writeup_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Check for lumping at the 0.15 cutoff</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>dwi_bin_count_0<span class="fl">.15</span> <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(bac_min <span class="sc">&gt;=</span> <span class="fl">0.10</span>, bac_min <span class="sc">&lt;=</span> <span class="fl">0.20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bac_bins =</span> <span class="fu">cut</span>(bac_min, <span class="at">breaks =</span> <span class="dv">10</span><span class="sc">:</span><span class="dv">20</span><span class="sc">/</span><span class="dv">100</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(bac_bins) <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>()</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Create plot to visualize the data</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dwi_bin_count_0<span class="fl">.15</span>, <span class="fu">aes</span>(<span class="at">x =</span> bac_bins, <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">5.5</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Observation counts near 0.15 BAC cutoff"</span>,</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"BAC bin"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="writeup_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Both of the bar charts above show that there is no obvious peak just beneath the 0.08 or 0.15 cutoff. This means that there is no indication that BAC levels have been manipulated to land on one side of the cutoff or the other. Both charts show a relatively consistent shape of the data, which means that we can trust that there is no manipulation in the running variable. We can now proceed with our placebo testing.</p>
</section>
<section id="run-placebo-tests" class="level2">
<h2 class="anchored" data-anchor-id="run-placebo-tests">Run Placebo Tests</h2>
<p>The second part of reviewing the data is to run placebo tests. We do this because we need to ensure that the other key RDD assumption is true, meaning that the only thing that changes at the cutoff is the punishment. To perform this test, we will re-run the RDD regressions but swap out recidivism with our other variables (male, white, aged, acc). If this key assumption holds, we should not expect to see any jump at the cutoff for any of these variables. If we do see a jump at the cutoff in any of these variables, then that would suggest that our two groups (above and below the threshold BAC level) differ in other ways, thus making our comparison invalid. We will perform this check for both the 0.08 BAC cutoff and the 0.15 BAC cutoff.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create centered variable for BAC at 0.08 cutoff</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dwi <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bac_centered_08 =</span> bac_min <span class="sc">-</span> <span class="fl">0.08</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Run regression for placebo tests at 0.08 cutoff</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">feols</span>(male <span class="sc">~</span> above_08<span class="sc">*</span>bac_centered_08, <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(white <span class="sc">~</span> above_08<span class="sc">*</span>bac_centered_08, <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">feols</span>(aged <span class="sc">~</span> above_08<span class="sc">*</span>bac_centered_08, <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">feols</span>(acc <span class="sc">~</span> above_08<span class="sc">*</span>bac_centered_08, <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(p1, p2, p3, p4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           p1                 p2
Dependent Var.:                          male              white
                                                                
Constant                   0.7853*** (0.0044) 0.8478*** (0.0039)
above_08                      0.0057 (0.0055)    0.0038 (0.0048)
bac_centered_08              -0.1752 (0.2321)    0.0552 (0.2029)
above_08 x bac_centered_08    0.2947 (0.2567)    0.0488 (0.2244)
__________________________ __________________ __________________
S.E. type                                 IID                IID
Observations                           92,158             92,158
R2                                    6.05e-5            8.86e-5
Adj. R2                                2.8e-5             5.6e-5

                                          p3                 p4
Dependent Var.:                         aged                acc
                                                               
Constant                   33.92*** (0.1265) 0.0825*** (0.0033)
above_08                    -0.1647 (0.1573)   -0.0022 (0.0041)
bac_centered_08            -66.52*** (6.622) -1.044*** (0.1730)
above_08 x bac_centered_08  73.75*** (7.324)  1.901*** (0.1914)
__________________________ _________________ __________________
S.E. type                                IID                IID
Observations                          92,158             92,158
R2                                   0.00232            0.00163
Adj. R2                              0.00229            0.00160
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>When looking at the above table, we can see that the coefficients on the above_08 variable are insignificant in all four of the placebo tests. This means that gender, race, age and whether there was an accident do not jump at the 0.08 cutoff. Because of this, we can confidently say that drivers above and below the BAC threshold and essentially identical for our purposes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Create centered variable for BAC at 0.15 cutoff</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>dwi <span class="ot">&lt;-</span> dwi <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">bac_centered_15 =</span> bac_min <span class="sc">-</span> <span class="fl">0.15</span>)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Run regression for placebo tests as 0.15 cutoff</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">feols</span>(male <span class="sc">~</span> above_15<span class="sc">*</span>bac_centered_15, <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_15) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>p6 <span class="ot">&lt;-</span> <span class="fu">feols</span>(white <span class="sc">~</span> above_15<span class="sc">*</span>bac_centered_15, <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_15) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>p7 <span class="ot">&lt;-</span> <span class="fu">feols</span>(aged <span class="sc">~</span> above_15<span class="sc">*</span>bac_centered_15, <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_15) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>p8 <span class="ot">&lt;-</span> <span class="fu">feols</span>(acc <span class="sc">~</span> above_15<span class="sc">*</span>bac_centered_15, <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_15) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(p5, p6, p7, p8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           p5                 p6
Dependent Var.:                          male              white
                                                                
Constant                   0.7891*** (0.0029) 0.8646*** (0.0025)
above_15                     -0.0013 (0.0042)    0.0044 (0.0036)
bac_centered_15             -0.1876. (0.1008)  0.2457** (0.0852)
above_15 x bac_centered_15    0.2263 (0.1558)   -0.1774 (0.1317)
__________________________ __________________ __________________
S.E. type                                 IID                IID
Observations                          138,308            138,308
R2                                    6.65e-5            0.00037
Adj. R2                               4.48e-5            0.00035

                                          p7                 p8
Dependent Var.:                         aged                acc
                                                               
Constant                   34.51*** (0.0821) 0.1438*** (0.0025)
above_15                     0.0560 (0.1191)   0.0068. (0.0037)
bac_centered_15             15.39*** (2.829) 0.9704*** (0.0868)
above_15 x bac_centered_15    9.989* (4.372)   0.2671* (0.1342)
__________________________ _________________ __________________
S.E. type                                IID                IID
Observations                         138,308            138,308
R2                                   0.00249            0.00865
Adj. R2                              0.00247            0.00863
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>When looking at the above table for the results of our 0.15 BAC placebo tests, we can say the same thing. The coefficients on the above_15 variable are not significant for gender, race, age, or whether there was an accident either. This means that there are no indications that other variables outside of the treatment or the outcome are jumping at the cutoff. We can proceed with running our regressions on the data.</p>
</section>
<section id="run-regressions" class="level2">
<h2 class="anchored" data-anchor-id="run-regressions">Run Regressions</h2>
<p>Now that we have checked the key assumptions in our data set, we can proceed with the main analysis. We want to determine whether crossing the BAC threshold, and receiving a harsh punishment, causes a decrease in recidivism. First, we will center the running variable around each cutoff point, create a treatment indicator for being above the threshold and then interact these two variables. The coefficient on the treatment indicator shows the jump in recidivism at the cutoff, which is our estimate of the effect of a harsher punishment. We will run three different variations for each cutoff: 1) a wider window of 0.05, 2) a narrower window of 0.02, and 3) a wide window with our additional variables added as controls. We will compare our results among these three variations to see if our results are stable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>r1 <span class="ot">&lt;-</span> <span class="fu">feols</span>(recidivism <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                            r1
Dependent Var.:                     recidivism
                                              
Constant                    0.1123*** (0.0034)
above_08                   -0.0188*** (0.0042)
bac_centered_08               -0.2613 (0.1772)
above_08 x bac_centered_08  0.6904*** (0.1960)
__________________________ ___________________
S.E. type                                  IID
Observations                            92,158
R2                                     0.00054
Adj. R2                                0.00051
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Based on the results of the above table for our first variation where we use a window of 0.05, the coefficient on above_08 is -0.0188 and higly significant at p &lt; 0.001. This means that drivers above the 0.08 threshold had a recidivism rate of about 1.9 percentage points lower than drivers below the cutoff. Since the overall recidivism rate is 11.8%, this decrease shows a significant drop in repeat offenders.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(recidivism <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.02</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           r2
Dependent Var.:                    recidivism
                                             
Constant                   0.1074*** (0.0045)
above_08                    -0.0133* (0.0062)
bac_centered_08             -0.8974* (0.4543)
above_08 x bac_centered_08    1.262* (0.5789)
__________________________ __________________
S.E. type                                 IID
Observations                           38,962
R2                                    0.00083
Adj. R2                               0.00075
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>When we narrow the window from 0.05 to 0.02, the coefficient on above_08 is -0.0133 and still significant at p &lt; 0.05. This result is smaller than our wider window of 0.05, nonetheless it still aligns with our result when we used the wider window.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>r3 <span class="ot">&lt;-</span> <span class="fu">feols</span>(recidivism <span class="sc">~</span> above_08 <span class="sc">*</span> bac_centered_08 <span class="sc">+</span> male <span class="sc">+</span> white <span class="sc">+</span> aged,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_08) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                             r3
Dependent Var.:                      recidivism
                                               
Constant                     0.1019*** (0.0054)
above_08                    -0.0192*** (0.0042)
bac_centered_08               -0.3129. (0.1770)
male                         0.0331*** (0.0025)
white                        0.0157*** (0.0029)
aged                       -0.0009*** (8.82e-5)
above_08 x bac_centered_08   0.7427*** (0.1958)
__________________________ ____________________
S.E. type                                   IID
Observations                             92,158
R2                                      0.00360
Adj. R2                                 0.00353
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>When we add our demographic variables as controls, the coefficient on above_08 at -0.0192 is very similar to our initial regression and equally significant at p&lt; 0.001. We have included these controls (male, white, aged) because they affect recidivism, but do not jump at the cutoff which we confirmed in our placebo tests. We do not include the acc variable as whether there was an accident or not can be influenced by the BAC variable. Given that our coefficients on above_08 have generally remained stable across the three variations, it improves our confidence that the effect is real.</p>
<p>We will now repeat our analysis from our first regression, using a wide window of 0.05, but not at the 0.15 threshold. If the belief that harsher penalties decrease drunk driving is true, we would expect to see a bigger drop in recidivism for drivers that receive harsher punishments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>r4 <span class="ot">&lt;-</span> <span class="fu">feols</span>(recidivism <span class="sc">~</span> above_15 <span class="sc">*</span> bac_centered_15,</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_15) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           r4
Dependent Var.:                    recidivism
                                             
Constant                   0.1206*** (0.0023)
above_15                    -0.0075* (0.0033)
bac_centered_15            0.3643*** (0.0795)
above_15 x bac_centered_15    0.0634 (0.1228)
__________________________ __________________
S.E. type                                 IID
Observations                          138,308
R2                                    0.00059
Adj. R2                               0.00057
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>At the 0.15 threshold using a wide window of 0.05, the coefficient on above_15 is -0.0075 and significant at p &lt; 0.05. This means that drivers above the 0.15 threshold had a recidivism rate of 0.75 percentage points lower than drivers below the cutoff. Although the effect is smaller than the one estimated at the 0.08 cutoff, it still supports the belief that harsher punishments decrease recidivism.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>r5 <span class="ot">&lt;-</span> <span class="fu">feols</span>(recidivism <span class="sc">~</span> above_15 <span class="sc">*</span> bac_centered_15,</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_15) <span class="sc">&lt;</span> <span class="fl">0.02</span>))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                           r5
Dependent Var.:                    recidivism
                                             
Constant                   0.1247*** (0.0037)
above_15                    -0.0103* (0.0052)
bac_centered_15             0.8516** (0.3099)
above_15 x bac_centered_15   -0.5693 (0.4542)
__________________________ __________________
S.E. type                                 IID
Observations                           60,584
R2                                    0.00014
Adj. R2                                9.1e-5
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>When we narrow to a 0.02 window, the coefficient on above_15 is -0.0103 and significant at p &lt; 0.05. Similar to our result of the narrow window on the above_08 cutoff, this estimate is somewhat noisier, however the direction and significance still align with our other results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>r6 <span class="ot">&lt;-</span> <span class="fu">feols</span>(recidivism <span class="sc">~</span> above_15 <span class="sc">*</span> bac_centered_15 <span class="sc">+</span> male <span class="sc">+</span> white <span class="sc">+</span> aged,</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> dwi <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">abs</span>(bac_centered_15) <span class="sc">&lt;</span> <span class="fl">0.05</span>))</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">etable</span>(r6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                             r6
Dependent Var.:                      recidivism
                                               
Constant                     0.1183*** (0.0044)
above_15                      -0.0075* (0.0033)
bac_centered_15              0.3799*** (0.0794)
male                         0.0292*** (0.0021)
white                          0.0055* (0.0025)
aged                       -0.0007*** (7.56e-5)
above_15 x bac_centered_15      0.0651 (0.1227)
__________________________ ____________________
S.E. type                                   IID
Observations                            138,308
R2                                      0.00265
Adj. R2                                 0.00260
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>When we add demographic controls, the coefficient on above_15 is -0.0075 (the same as our first estimate for the 0.15 cutoff) and is significant at p &lt; 0.05. Just like our regression with controls at the 0.08 cutoff, the addition of these controls do not materially change our results, which is what we would expect to see given the results of our placebo tests.</p>
<p>Putting it all together, the above results show us similar effects. Crossing the first cutoff of 0.08 reduces recidivism by about 1.9 percentage points, and crossing the 0.15 cutoff reduces recidivism by an additional 0.75 percentage points. Both of these effects are statistically significant and remain consistent across different window sizes and the addition of demographic controls. Therefore, we can say that harsher punishments do reduce the likelihood of re-offending.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>